export const poolsPlaceholder: PoolTable[] = [
  {
    id: 1,
    name: "WETH",
    icon1: "/eth-icon.svg",
    icon2: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 2,
    name: "WBTC",
    icon1: "/eth-icon.svg",
    icon2: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 3,
    name: "USDC",
    icon1: "/eth-icon.svg",
    icon2: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 4,
    name: "USDT",
    icon1: "/eth-icon.svg",
    icon2: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 5,
    name: "DAI",
    icon1: "/eth-icon.svg",
    icon2: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
];

export const poolDetailsPlaceholder = [
  {
    label: "DEPOSIT APY 7D",
    value: "2.18%",
    tooltip: "Average Deposit APY for the last 7 days",
  },
  {
    label: "DEPOSIT APY 30D",
    value: "1.69%",
    tooltip: "Average Deposit APY for the last 30 days",
  },
  { 
    label: "DIESEL RATE", 
    value: "1.055073",
    tooltip: "Current Diesel Rate"
  },
  {
    label: "EXPECTED LIQUIDITY",
    value: "19.15K ETH",
    tooltip: "Expected liquidity in the pool",
  },
  {
    label: "BORROW APY",
    value: "1.94%",
    tooltip: "Current Borrow Annual Percentage Yield",
  },
  {
    label: "TOTAL BORROWED",
    value: "10.32K ETH",
    tooltip: "Total amount borrowed from the pool",
  },
  {
    label: "AVAILABLE LIQUIDITY",
    value: "8.74K ETH",
    tooltip: "Current available liquidity in the pool",
  },
  {
    label: "UNIQUE USERS",
    value: "1955",
    tooltip: "Number of unique users in the pool",
  },
  {
    label: "WITHDRAWAL FEES",
    value: "0.00%",
    tooltip: "Current withdrawal fees",
  },
];
