export const poolsPlaceholder: PoolTable[] = [
  {
    id: 1,
    name: "WETH",
    icon: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 2,
    name: "WBTC",
    icon: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 3,
    name: "USDC",
    icon: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 4,
    name: "USDT",
    icon: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
  {
    id: 5,
    name: "DAI",
    icon: "/eth-icon.svg",
    supply: "-",
    supplyAPY: "-",
    borrowAPY: "-",
    yourBalance: "-",
    isActive: false,
    version: 0,
  },
];

export const poolDetailsPlaceholder = [
  {
    label: "SUPPLY APY",
    value: "-",
    tooltip: "Average Deposit APY for the last 7 days",
  },
  {
    label: "BORROW APY",
    value: "-",
    tooltip: "Current Borrow Annual Percentage Yield",
  },
  { 
    label: "VTOKEN RATE", 
    value: "-",
    tooltip: "Current Diesel Rate"
  },
  {
    label: "TOTAL LIQUIDITY",
    value: "-",
    tooltip: "Expected liquidity in the pool",
  },
  {
    label: "LQ. IN DOLLAR",
    value: "-",
    tooltip: "Expected liquidity in the pool",
  },
  {
    label: "TOTAL BORROWED",
    value: "-",
    tooltip: "Total amount borrowed from the pool",
  },
  {
    label: "AVAILABLE LIQUIDITY",
    value: "-",
    tooltip: "Current available liquidity in the pool",
  },
  {
    label: "UNIQUE USERS",
    value: "-",
    tooltip: "Number of unique users in the pool",
  },
  {
    label: "WITHDRAWAL FEES",
    value: "-",
    tooltip: "Current withdrawal fees",
  },
];
